{
  "SOX10": "soks on",
  "S100": "es yüz",
  "mukuslu": "müsinöz",
  "MYC": "mik",
  "MAP": "map",
  "HCC": "hecece",
  "Helicobacter": "helikobakter",
  "NUT": "nut",
  "Papanicolaou": "Papanikolau",
  "β": "beta",
  "SWI": "seve i",
  "Hodgkin": "Hoçkin",
  "NGS": "enci es",
  "INI1": "ını 1",
  "CASTLE": "kestıl",
  "Verruciform": "Verrusiform",
  "MLH1": "me le aş bir",
  "STIC": "sıtik",
  "Curvularia": "Kurvularya",
  "MSI-H": "emesay hay",
  "HPV'den": "hepeveden",
  "MD Anderson": "emdi andırsın",
  "miRNA": "mirene a",
  "PI3K": "pi ay tiri kay",
  "IDH1": "i de aş bir",
  "neoplazm": "neoplazi",
  "DICER1": "daysırvan"
}
